### ISSUE TITLE
Milestone 1 Pages

### ISSUE THREAD

**Issue by Oculux314** [UoaWDCC/nzpmc-exam-portal#302]
### Description:

Check the milestone 1 pages and make sure they're implemented well, consistently, and without bugs.
- [ ] App
- [ ] 404
- [ ] Mobile
- [ ] Auth (note: blocked by # - check once complete)

### Acceptance Criteria:
- [ ] All pages checked for **bugs**
- [ ] All pages use good **code style**
- [ ] **Iconify/vuetify** used & consistent across pages
- [ ] **Scss variable theming** used & consistent across pages
- [ ] **Scss globals** (e.g. fonts) / **mixins** used & consistent across pages

### Definition of Done:
- [ ] AC met
- [ ] PR linked
- [ ] Branch merged

### Notes
