### ISSUE TITLE
362 Document Mutations

### ISSUE THREAD

**Issue by johnchen383** [UoaWDCC/nzpmc-exam-portal#364]
### Acceptance Criteria:
- [ ] How to write mutations is well documented

### Definition of Done:
- [ ] AC met
- [ ] Approved by PM
- [ ] Issue closed

### Notes

```[tasklist]
### Tasks
- [ ] https://github.com/UoaWDCC/nzpmc-exam-portal/wiki/Learning
```

**Comment by Oculux314** [comment]
Looks great!

TODO explain interaction between schema files and codegen
^ I'll mark this as complete and this remaining part can be a separate ticket if nobody else gets to it first.
